### ISSUE TITLE
getVoxels unimplemented in AbstractVirtualStack

### ISSUE THREAD

**Issue by ctrueden** [imglib/imglib2-ij#27]
Consider this Groovy script:
```groovy
image = net.imglib2.img.array.ArrayImgs.unsignedBytes(10, 10, 10)
imp = net.imglib2.img.display.imagej.ImageJFunctions.wrap(image, "Image")
ij.IJ.run(imp, "Gaussian Blur 3D...", "x=10 y=2 z=2")
```
Running it results in the following exception:
```
java.lang.UnsupportedOperationException
	at net.imglib2.img.display.imagej.AbstractVirtualStack.getVoxels(AbstractVirtualStack.java:351)
	at ij.plugin.GaussianBlur3D.blurZ(GaussianBlur3D.java:72)
	at ij.plugin.GaussianBlur3D.blur(GaussianBlur3D.java:55)
	at ij.plugin.GaussianBlur3D.run(GaussianBlur3D.java:20)
	at ij.IJ.runPlugIn(IJ.java:198)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at ij.IJ.run(IJ.java:308)
	at ij.IJ.run(IJ.java:364)
	at ij.IJ$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at Script8.run(Script8.groovy:6)
```

**Comment by ctrueden** [comment]
Should be fixed now thanks to #28.
